# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Rsync Deployments Action
        # You may pin to the exact commit or the version.
        # uses: Burnett01/rsync-deployments@0dc935cdecc5f5e571865e60d2a6cdc673704823
        uses: Burnett01/rsync-deployments@5.2
        with:
          # The switches
          switches: -avzr --delete --exclude=".git" --exclude=".github"
          # The local path
          path: /
          # The remote path
          remote_path: /home/kanadeex/public_html/ppdb
          # The remote host
          remote_host: ppdb.kanadee.xyz
          # The remote port
          remote_port: 423
          # The remote user
          remote_user: kanadeex
          # The remote key
          remote_key: ${{secrets.DEPLOY_KEY}}
          # The remote key passphrase
          remote_key_pass: habib18102002
